[package]
name = "file-structure"
version = "0.1.1"
authors = ["João M. Bezerra <marcospb19@hotmail.com>"]
edition = "2018"
description = "Abandoned crate, name is free to use."
repository = "https://github.com/marcospb19/file-structure"
license = "MIT"
